In [2]:
import pandas as pd
from scipy import stats

url = "https://raw.githubusercontent.com/nkmwicz/worldcup2018data/refs/heads/main/cleaned_events_world_cup2018.csv"
# https://raw.githubusercontent.com/nkmwicz/worldcup2018data/refs/
# heads/main/cleaned_events_world_cup2018.csv
df = pd.read_csv(url)
df.head(1)

,eventId,subEventName,tags,playerId,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id,x1,y1,x2,y2
0,8,Simple pass,['Accurate'],Mohammad Ibrahim Al Sahlawi,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,1.656214,Simple pass,258612104,50,50,35.0,53.0

In [7]:
var = ["string"]
type(var)

list

In [8]:
import ast
df["tags"] = df["tags"].apply(ast.literal_eval)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101759 entries, 0 to 101758
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   eventId       101759 non-null  int64
 1   subEventName  101587 non-null  str
 2   tags          101759 non-null  object
 3   playerId      101759 non-null  str
 4   matchId       101759 non-null  str
 5   eventName     101759 non-null  str
 6   teamId        101759 non-null  str
 7   matchPeriod   101759 non-null  str
 8   eventSec      101759 non-null  float64
 9   subEventId    101587 non-null  str
 10  id            101759 non-null  int64
 11  x1            101759 non-null  int64
 12  y1            101759 non-null  int64
 13  x2            101755 non-null  float64
 14  y2            101755 non-null  float64
dtypes: float64(3), int64(4), object(1), str(7)
memory usage: 11.6+ MB

In [11]:
from python_classwork_f2026.evaluate_df import evaluate_df

df["eventName"].unique()

<StringArray>
[                   'Pass',                    'Duel',
               'Free Kick',                    'Foul',
      'Others on the ball',                    'Shot',
            'Save attempt',                 'Offside',
 'Goalkeeper leaving line']
Length: 9, dtype: str

In [12]:
df['subEventName'].unique()

<StringArray>
[            'Simple pass',               'High pass',
                'Air duel',   'Ground attacking duel',
   'Ground defending duel',                'Throw in',
                    'Foul',               'Free Kick',
               'Clearance',                   'Touch',
  'Ground loose ball duel',                  'Corner',
               'Head pass',                  'Launch',
            'Acceleration',                    'Shot',
              'Smart pass',                   'Cross',
                'Reflexes',                       nan,
               'Hand pass',               'Goal kick',
         'Free kick cross',               'Hand foul',
            'Save attempt',          'Free kick shot',
 'Goalkeeper leaving line',                 'Penalty',
          'Late card foul',            'Violent Foul',
                 'Protest',        'Out of game foul',
          'Time lost foul',              'Simulation']
Length: 34, dtype: str

In [ ]:
unique_tags = list(set([tag for lst in df["tags"] for tag in lst]))
# unique_tags = list({tag for lst in df["tags"] for tag in lst})

unique_tags
# for l in df["tags"]:
#     for t in l:
#         print(t)

['Goal',
 'Position: Goal center left',
 'Position: Post low left',
 'Left foot',
 'Position: Out high center',
 'Interception',
 'Red card',
 'Position: Goal low right',
 'Accurate',
 'Feint',
 'Anticipated',
 'Position: Goal high center',
 'Position: Out low right',
 'Key pass',
 'Take on left',
 'Right foot',
 'Position: Post center left',
 'Yellow card',
 'Direct',
 'Free space right',
 'Opportunity',
 'Free space left',
 'Neutral',
 'Own goal',
 'Through',
 'Take on right',
 'Position: Goal high left',
 'Won',
 'High',
 'Anticipation',
 'Lost',
 'Position: Goal high right',
 'Assist',
 'Position: Goal low left',
 'Position: Post center right',
 'Position: Out center left',
 'Dangerous ball lost',
 'Second yellow card',
 'Position: Goal center right',
 'Position: Out low left',
 'Position: Post high right',
 'Sliding tackle',
 'Blocked',
 'Position: Out high right',
 'Position: Out center right',
 'Fairplay',
 'Head/body',
 'Position: Post high center',
 'Position: Goal center',
 'Counter attack',
 'Position: Out high left',
 'Position: Goal low center',
 'Missed ball',
 'Not accurate',
 'Position: Post high left',
 'Position: Post low right',
 'Indirect']

In [22]:
df['is_pass'] = (df['eventName'] == "Pass").astype(int)
df['is_pass']

0         1
1         1
2         0
3         0
4         1
         ..
101754    1
101755    0
101756    1
101757    0
101758    1
Name: is_pass, Length: 101759, dtype: int64

In [23]:
df.head()

,eventId,subEventName,tags,playerId,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id,x1,y1,x2,y2,is_pass
0,8,Simple pass,[Accurate],Mohammad Ibrahim Al Sahlawi,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,1.656214,Simple pass,258612104,50,50,35.0,53.0,1
1,8,High pass,[Accurate],Abdullah Ibrahim Otayf,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,4.487814,High pass,258612106,35,53,75.0,19.0,1
2,1,Air duel,"[Won, Accurate]",Ilya Kutepov,"Russia - Saudi Arabia, 5 - 0",Duel,Russia,1H,5.937411,Air duel,258612077,25,81,37.0,83.0,0
3,1,Air duel,"[Lost, Not accurate]",Yasir Gharsan Al Shahrani,"Russia - Saudi Arabia, 5 - 0",Duel,Saudi Arabia,1H,6.406961,Air duel,258612112,75,19,63.0,17.0,0
4,8,Simple pass,[Accurate],Salman Mohammed Al Faraj,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,8.562167,Simple pass,258612110,63,17,71.0,15.0,1

In [26]:
df["is_shot"] = (df["eventName"] == "Shot").astype(int)
df.head()

,eventId,subEventName,tags,playerId,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id,x1,y1,x2,y2,is_pass,is_shot
0,8,Simple pass,[Accurate],Mohammad Ibrahim Al Sahlawi,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,1.656214,Simple pass,258612104,50,50,35.0,53.0,1,0
1,8,High pass,[Accurate],Abdullah Ibrahim Otayf,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,4.487814,High pass,258612106,35,53,75.0,19.0,1,0
2,1,Air duel,"[Won, Accurate]",Ilya Kutepov,"Russia - Saudi Arabia, 5 - 0",Duel,Russia,1H,5.937411,Air duel,258612077,25,81,37.0,83.0,0,0
3,1,Air duel,"[Lost, Not accurate]",Yasir Gharsan Al Shahrani,"Russia - Saudi Arabia, 5 - 0",Duel,Saudi Arabia,1H,6.406961,Air duel,258612112,75,19,63.0,17.0,0,0
4,8,Simple pass,[Accurate],Salman Mohammed Al Faraj,"Russia - Saudi Arabia, 5 - 0",Pass,Saudi Arabia,1H,8.562167,Simple pass,258612110,63,17,71.0,15.0,1,0

In [27]:
df.columns

Index(['eventId', 'subEventName', 'tags', 'playerId', 'matchId', 'eventName',
       'teamId', 'matchPeriod', 'eventSec', 'subEventId', 'id', 'x1', 'y1',
       'x2', 'y2', 'is_pass', 'is_shot'],
      dtype='str')

In [34]:
groupbys = [
    ["teamId", "matchId"],
    ["teamId"],
    ["matchId"]
]

for grp in groupbys:
    new_g = df.groupby(grp).agg(
        passes=("is_pass", "sum"),
        shots=("is_shot", "sum"),
        games=("matchId", "nunique"),
    ).reset_index()
    r, p = stats.pearsonr(new_g["passes"], new_g["shots"])
    r2 = r**2
    print(f"{grp}: ")
    print(f"\tr:{r:.4f}, p:{p:.4f}, r2: {r2:.4f}")
    if grp == ["teamId"]:
        norm_new_g = new_g.copy()
        norm_new_g["pass_p_g"] = norm_new_g["passes"] / norm_new_g["games"]
        norm_new_g["shot_p_g"] = norm_new_g["shots"] / norm_new_g["games"]
        r1, p1 = stats.pearsonr(norm_new_g["pass_p_g"], norm_new_g["shot_p_g"])
        r21 = r1**2
        print(f"norm_{grp}: ")
        print(f"\tr:{r1:.4f}, p:{p1:.4f}, r2: {r21:.4f}")

['teamId', 'matchId']:
	r:0.5642, p:0.0000, r2: 0.3184
['teamId']:
	r:0.8932, p:0.0000, r2: 0.7979
norm_['teamId']:
	r:0.6667, p:0.0000, r2: 0.4445
['matchId']:
	r:0.1996, p:0.1138, r2: 0.0398